# Configurable planning providers

Planning needs weather, places, events, and itinerary text. The GraphQL service owns those four capabilities behind narrow TypeScript ports with Zod response schemas. A single selector reads validated `PROVIDER_WEATHER`, `PROVIDER_PLACES`, `PROVIDER_EVENTS`, and `PROVIDER_LLM` values at startup. Each defaults to a deterministic mock, so a fresh local GraphQL query needs no vendor account or network call.

For example, `PROVIDER_WEATHER=wttr` selects the wttr JSON adapter while places, events, and LLM can stay mocked. The real adapters are wttr, Overpass, Ticketmaster, OpenAI, and Anthropic. The selector constructs only selected adapters; their keys and model names are required only when selected. Weather, place, and event requests use bounded response reads, timeouts, and at most two read retries with jitter. LLM adapters use their SDK streaming APIs, propagate abort signals, and cap collected output at 4,000 characters. `PROVIDER_TIMEOUT_MS` bounds the wait for the first stream event and for each later one, and `PROVIDER_STREAM_DEADLINE_MS` (default 60 s) bounds the whole stream, so a slow but steady stream finishes while a stalled one fails as a timeout. The business resolver receives only the port bundle and never handles vendor response shapes.

The trip service uses weather, places and events results as activity ideas when `createTrip` or `refineTrip` plans days; the earlier `planTrip` prototype query has been removed. The LLM port is kept for streamed itinerary text. Provider failures are normalized to safe categories before Yoga masks them; raw vendor payloads, prompts, keys, and exceptions are not logged. Automatic LLM stream retries are avoided because replaying a partially emitted generation could duplicate or change output.

Run the GraphQL tests with installed dependencies to exercise deterministic mocks and injected transports for successful responses, malformed data, timeouts, rate limits, and interrupted streams. The OpenAI adapter follows the [official streaming event guide](https://developers.openai.com/api/docs/guides/streaming-responses); no live vendor test runs by default. Live provider checks are opt-in account steps after credentials are supplied.
